<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Atelia.RecordClassFactsLibrary</AssemblyName>
    <PackageId>Atelia.RecordClassFactsLibrary</PackageId>
    <WarningsAsErrors>$(WarningsAsErrors);CS0433;CS0436</WarningsAsErrors>
    <HistoryVersion Condition="'$(HistoryVersion)' == ''">1</HistoryVersion>
    <DefineConstants>$(DefineConstants);HISTORY_V$(HistoryVersion)</DefineConstants>
    <DurableGraphGenerateDefinitions>true</DurableGraphGenerateDefinitions>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackModelReferenceAssembly</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Atelia.DurableGraph" Version="$(DurableGraphPackageVersion)" />
    <PackageReference Include="Atelia.RecordClassBaseLibrary" Version="$(ModelPackageVersion)" />
  </ItemGroup>
  <Target Name="PackModelReferenceAssembly">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(IntermediateOutputPath)ref/$(TargetFileName)" PackagePath="ref/$(TargetFramework)" />
    </ItemGroup>
  </Target>
</Project>
