using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Atelia.DurableGraph.SchemaHistory;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Atelia.DurableGraph.Generator;

public sealed partial class DurableSchemaGenerator {
    private static void GenerateGenericStates(SourceProductionContext context, List<DurableTypeModel> types,
        List<SchemaHistoryModel> history, bool historyParsedSuccessfully, Compilation compilation) {
        if (!historyParsedSuccessfully) return;
        List<SchemaHistoryModel> available = new(history);
        foreach (DurableTypeModel type in types) {
            available.RemoveAll(shape => shape.SchemaId == type.SchemaId && shape.Version == type.Version);
            available.Add(CurrentShape(type));
        }
        available = available.GroupBy(shape => (shape.SchemaId, shape.Version)).Select(group => group.First())
            .OrderBy(shape => shape.SchemaId, StringComparer.Ordinal).ThenBy(shape => shape.Version).ToList();
        Dictionary<string, List<GenericLayout>> families = new(StringComparer.Ordinal);
        foreach (SchemaHistoryModel shape in available) {
            if (!families.TryGetValue(shape.SchemaId, out List<GenericLayout>? versions)) {
                versions = new(); families.Add(shape.SchemaId, versions);
            }
            versions.Add(MakeGenericLayout(shape, available));
        }
        StringBuilder output = new("// <auto-generated/>\n#nullable enable\n");
        output.AppendLine("namespace Atelia.DurableGraph.Generated {");
        foreach (KeyValuePair<string, List<GenericLayout>> family in families) {
            output.Append("public static class ").Append(FamilyName(family.Key)).AppendLine(" {");
            foreach (GenericLayout layout in family.Value) {
                AppendGenericDto(output, layout);
                AppendGenericBody(output, layout);
                AppendGenericHistoricalFactory(output, layout);
            }
            AppendGenericFamilyDefinition(output, family.Value, types, compilation, context);
            output.AppendLine("}");
        }
        output.AppendLine("public static class DurableDefinitions {");
        output.Append("    public static void Register(").Append(RuntimeName).AppendLine("IStateDefinitionRegistration definitions) {");
        output.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(definitions);");
        foreach (string id in families.Keys) output.Append("        definitions.Register(").Append(FamilyName(id)).AppendLine(".Definition);");
        foreach (INamedTypeSymbol rules in GetValueRuleSets(compilation)) {
            output.Append("        definitions.Register(").Append(ValueRuleSetClassName(rules)).AppendLine(".Rules);");
        }
        output.AppendLine("    }");
        output.AppendLine("}");
        AppendValueUpgradeRuleSets(output, types, history, compilation, context);
        output.AppendLine("}");
        foreach (DurableTypeModel type in types) {
            GenericLayout layout = families[type.SchemaId].Single(item => item.Shape.Version == type.Version);
            AppendGenericDomainProjection(output, type, layout, types);
        }
        context.AddSource("DurableGenericStates.g.cs", SourceText.From(output.ToString().Replace("\r\n", "\n"), Encoding.UTF8));
    }

    private static void AppendGenericHistoricalFactory(StringBuilder output, GenericLayout layout) {
        string resultType = RuntimeName + (layout.Shape.Kind == 2 ? "StateValueBinding" : "StateReaderBinding");
        string name = "CreateHistorical" + layout.Name;
        output.Append("    private static ").Append(resultType).Append(' ').Append(name).Append('(').Append(RuntimeName)
            .Append("DurableSchema schema, ").Append(RuntimeName).AppendLine("StateBindingContext context) {");
        output.AppendLine("        var binding = context.BindSchema(schema);");
        for (int index = 0; index < layout.DynamicFields.Count; index++) {
            GenericField field = layout.DynamicFields[index];
            output.Append("        var value").Append(index).Append(" = binding.GetValue(");
            AppendTypePatternExpression(output, field.Pattern);
            if (field.Field.InlineSchema is SchemaReference inline) output.Append(", ").Append(inline.Version);
            output.AppendLine(");");
        }
        if (layout.DynamicFields.Count == 0) output.Append("        return ").Append(name).AppendLine("Typed(schema, context);");
        else {
            output.Append("        var method = typeof(").Append(FamilyName(layout.Shape.SchemaId)).Append(").GetMethod(")
                .Append(Literal(name + "Typed")).Append(", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic)!")
                .Append(".MakeGenericMethod(").Append(string.Join(", ", Enumerable.Range(0, layout.DynamicFields.Count).SelectMany(index => new[] { "value" + Number(index) + ".StateType", "value" + Number(index) + ".StateOpsType" }))).AppendLine(");");
            output.Append("        return method.CreateDelegate<global::System.Func<").Append(RuntimeName).Append("DurableSchema, ").Append(RuntimeName)
                .Append("StateBindingContext, ").Append(resultType).AppendLine(">>()(schema, context);");
        }
        output.AppendLine("    }");
        output.Append("    private static ").Append(resultType).Append(' ').Append(name).Append("Typed").Append(layout.OperationParameters)
            .Append('(').Append(RuntimeName).Append("DurableSchema schema, ").Append(RuntimeName).Append("StateBindingContext context)");
        AppendGenericConstraints(output, layout, true);
        output.AppendLine(" {");
        if (layout.Shape.Kind == 2) {
            output.Append("        return new ").Append(RuntimeName).Append("StateValueBinding(new ").Append(RuntimeName)
                .Append("DurableFieldInfo(1, ").Append(RuntimeName).Append("TypeTag.InlineValue, inlineSchema: schema), typeof(").Append(layout.Dto)
                .Append("), typeof(").Append(layout.Body).AppendLine("));");
        } else {
            output.Append("        return new ").Append(RuntimeName).Append("StateReaderBinding<").Append(layout.Dto).AppendLine(">(schema,");
            output.Append("            (ref ").Append(PayloadNamespace).Append("BinaryPayloadReader reader) => ").Append(layout.Body).AppendLine(".Read(ref reader, schema),");
            output.Append("            (ref ").Append(PayloadNamespace).Append("BinaryPayloadReader reader, in ").Append(layout.Dto).Append(" prior) => ")
                .Append(layout.Body).AppendLine(".Apply(ref reader, in prior, schema),");
            output.Append("            (in ").Append(layout.Dto).Append(" state, ").Append(RuntimeName).Append("IStateReferenceVisitor visitor) => ")
                .Append(layout.Body).AppendLine(".Visit(in state, visitor, schema));");
        }
        output.AppendLine("    }");
    }

    private static void AppendGenericFamilyDefinition(StringBuilder output, List<GenericLayout> versions,
        List<DurableTypeModel> types, Compilation compilation, SourceProductionContext context) {
        string id = versions[0].Shape.SchemaId;
        DurableTypeModel? domain = types.Where(type => type.SchemaId == id).Select(type => (DurableTypeModel?)type).FirstOrDefault();
        SchemaHistoryModel latest = versions[versions.Count - 1].Shape;
        string kind = latest.Kind == 2 ? "InlineValue" : "ReferenceObject";
        output.Append("    public static readonly ").Append(RuntimeName).Append("StateDefinitionBinding Definition = new(")
            .Append(Literal(id)).Append(", ").Append(RuntimeName).Append("SchemaKind.").Append(kind).Append(", ").Append(latest.Arity).Append(", ")
            .Append(domain.HasValue ? "typeof(" + UnboundDomainType(domain.Value.Symbol) + ")" : "null")
            .Append(", new ").Append(RuntimeName).AppendLine("StateSchemaTemplate[] {");
        foreach (GenericLayout version in versions) {
            SchemaHistoryModel shape = version.Shape;
            output.Append("        new(").Append(Literal(id)).Append(", ").Append(shape.Version).Append(", ").Append(RuntimeName).Append("SchemaKind.").Append(kind)
                .Append(", ").Append(shape.Arity).Append(", new ").Append(RuntimeName).AppendLine("StateFieldTemplate[] {");
            foreach (SchemaHistoryFieldModel field in shape.Fields) {
                output.Append("            new(").Append(field.FieldId).Append(", ");
                AppendTypePatternExpression(output, field.ValuePattern);
                if (field.InlineSchema is SchemaReference inline) output.Append(", ").Append(inline.Version);
                output.AppendLine("),");
            }
            output.Append("        }");
            if (shape.BaseSchema is SchemaReference ancestor) {
                output.Append(", new ").Append(RuntimeName).Append("StateSchemaReference(");
                AppendTypePatternExpression(output, ancestor.Type);
                output.Append(", ").Append(ancestor.Version).Append(')');
            }
            output.Append(", stateTypeDefinition: typeof(").Append(version.Name);
            if (version.DynamicFields.Count > 0) output.Append('<').Append(new string(',', version.DynamicFields.Count - 1)).Append('>');
            output.Append("), stateParameters: new ").Append(RuntimeName).AppendLine("StateParameterTemplate[] {");
            foreach (GenericField operand in version.DynamicFields) {
                output.Append("            new(");
                AppendTypePatternExpression(output, operand.Pattern);
                if (operand.Field.InlineSchema is SchemaReference dependency) output.Append(", ").Append(dependency.Version);
                output.AppendLine("),");
            }
            output.Append("        }");
            output.AppendLine("),");
        }
        output.AppendLine("    },");
        if (domain.HasValue) {
            string callback = latest.Kind == 2 ? "currentValueFactory" : "currentModelFactory";
            string result = RuntimeName + (latest.Kind == 2 ? "StateValueBinding" : "StateModelBinding");
            output.Append("    ").Append(callback).AppendLine(": static (domain, context) => {");
            if (domain.Value.IsEnum) {
                output.Append("        return ").Append(EnumProjectionHost(domain.Value.SchemaId)).AppendLine(".CreateCurrent(context);");
            } else {
                output.Append("        var method = domain.GetMethod(\"__DurableCreateCurrent\", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.DeclaredOnly)!;").AppendLine();
                output.Append("        return method.CreateDelegate<global::System.Func<").Append(RuntimeName).Append("StateBindingContext, ").Append(result).AppendLine(">>()(context);");
            }
            output.AppendLine("    },");
        }
        output.Append("    ").Append(latest.Kind == 2 ? "historicalValueFactory" : "historicalReaderFactory").AppendLine(": static (schema, context) => schema.Version switch {");
        foreach (GenericLayout version in versions) output.Append("        ").Append(version.Shape.Version).Append(" => CreateHistorical").Append(version.Name).AppendLine("(schema, context),");
        output.AppendLine("        _ => throw new global::System.IO.InvalidDataException(\"No exact generated historical version exists.\"),");
        output.Append("    }");
        AppendGenericUpgradeProviders(output, domain, versions, compilation, context);
        output.AppendLine(");");
    }

    private static string UnboundDomainType(INamedTypeSymbol type) =>
        type.Arity == 0 ? type.ToDisplayString(GenericQualifiedNameFormat) : type.ConstructUnboundGenericType().ToDisplayString(GenericQualifiedNameFormat);

    private static string DomainParameters(INamedTypeSymbol type) => GenericList(type.TypeParameters.Select(parameter => EscapeIdentifier(parameter.Name)));

    private static string DomainConstraints(INamedTypeSymbol type) {
        StringBuilder output = new();
        foreach (ITypeParameterSymbol parameter in type.TypeParameters) {
            List<string> constraints = new();
            if (parameter.HasUnmanagedTypeConstraint) constraints.Add("unmanaged");
            else if (parameter.HasValueTypeConstraint) constraints.Add("struct");
            else if (parameter.HasReferenceTypeConstraint) constraints.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            else if (parameter.HasNotNullConstraint) constraints.Add("notnull");
            constraints.AddRange(parameter.ConstraintTypes.Select(constraint => constraint.ToDisplayString(GenericQualifiedNameFormat)));
            if (parameter.HasConstructorConstraint) constraints.Add("new()");
            if (constraints.Count > 0) output.Append(" where ").Append(EscapeIdentifier(parameter.Name)).Append(" : ").Append(string.Join(", ", constraints));
        }
        return output.ToString();
    }
}
