using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Atelia.DurableGraph.SchemaHistory;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Atelia.DurableGraph.Generator;

public sealed partial class DurableSchemaGenerator {
    private const string SchemaExportAttributeName = "Atelia.DurableGraph.DurableSchemaExportAttribute";
    private static readonly DiagnosticDescriptor InvalidSchemaExport = new(
        "DG0023", "Invalid referenced durable schema material", "Referenced durable schema material is invalid: {0}",
        "DurableGraph.Generator", DiagnosticSeverity.Error, true);

    private static string RenderTemplateManifest(SchemaHistoryModel shape) {
        StringBuilder output = new();
        output.AppendLine(SchemaHistoryManifestHeader).AppendLine("// schema-begin");
        output.Append("// schema-id-base64:").AppendLine(Convert.ToBase64String(StrictUtf8.GetBytes(shape.SchemaId)));
        output.Append("// version:").AppendLine(Number(shape.Version));
        output.Append("// kind:").AppendLine(Number(shape.Kind));
        output.Append("// arity:").AppendLine(Number(shape.Arity));
        if (shape.BaseSchema is SchemaReference ancestor)
            output.Append("// base:").Append(ancestor.Type).Append('|').AppendLine(Number(ancestor.Version));
        foreach (SchemaHistoryFieldModel field in shape.Fields) {
            output.Append("// field:").Append(Number(field.FieldId)).Append('|').Append(Number(field.TypeTagValue));
            if (!TypePattern.IsBuiltinTag(field.TypeTagValue)) output.Append('|').Append(field.ValuePattern);
            if (field.InlineSchema is SchemaReference inline) output.Append('|').Append(Number(inline.Version));
            output.AppendLine();
        }
        return output.AppendLine("// schema-end").ToString().Replace("\r\n", "\n");
    }

    private static void GenerateSchemaExports(SourceProductionContext context, IEnumerable<SchemaHistoryModel> owned) {
        SchemaHistoryModel[] shapes = owned.ToArray();
        if (shapes.Length == 0) return;
        StringBuilder output = new("// <auto-generated/>\n");
        foreach (SchemaHistoryModel shape in shapes) {
            output.Append("[assembly: global::").Append(SchemaExportAttributeName).Append('(').Append(shape.Kind == 2 ? 1 : 2).Append(", ")
                .Append(Literal(shape.SchemaId)).Append(", ").Append(Number(shape.Version)).Append(", ")
                .Append(Literal(RenderTemplateManifest(shape))).AppendLine(")]");
        }
        context.AddSource("DurableGraphSchemaExports.g.cs", SourceText.From(output.ToString(), Encoding.UTF8));
    }

    private sealed class SchemaExport {
        internal SchemaExport(IAssemblySymbol owner, AttributeData attribute) { Owner = owner; Attribute = attribute; }
        internal IAssemblySymbol Owner { get; }
        internal AttributeData Attribute { get; }
    }

    private static INamedTypeSymbol InlineDomain(DurableFieldModel field) =>
        (INamedTypeSymbol)(IsNullableValue(field.Symbol.Type) ? ((INamedTypeSymbol)field.Symbol.Type).TypeArguments[0] : field.Symbol.Type);

    private static bool TryImportSchemaReferences(SourceProductionContext context, Compilation compilation,
        List<DurableTypeModel> types, List<SchemaHistoryModel> history,
        out List<SchemaHistoryModel> references, out string? manifest) {
        List<SchemaHistoryModel> selected = new();
        references = selected;
        manifest = SchemaHistoryReferenceProtocol.Render(Array.Empty<SchemaHistoryReferenceEntry>());
        HashSet<string> owned = new(history.Select(shape => shape.SchemaId), StringComparer.Ordinal);
        foreach (DurableTypeModel type in types) owned.Add(type.SchemaId);
        // Purely local compilations need no metadata import index (and retain their existing diagnostics).
        bool currentExternal = types.Any(type => (GetCurrentBaseReference(type).HasValue &&
            !SymbolEqualityComparer.Default.Equals(type.Symbol.BaseType!.ContainingAssembly, compilation.Assembly)) || type.Fields.Any(field => field.InlineSchema.HasValue &&
            !SymbolEqualityComparer.Default.Equals(InlineDomain(field).ContainingAssembly, compilation.Assembly)));
        bool historicalExternal = history.Any(shape => (shape.BaseSchema is SchemaReference ancestor && !owned.Contains(ancestor.SchemaId)) ||
            shape.Fields.Any(field => field.InlineSchema is SchemaReference inline && !owned.Contains(inline.SchemaId)));
        IMethodSymbol[] rules = GetValueUpgradeMethods(compilation).ToArray();
        bool rulesExternal = rules.Any(method => GetAttribute(method.GetAttributes(), ValueProviderAttributeName)!.ConstructorArguments is var args &&
            args.Length == 4 && args[1].Value is string id && !owned.Contains(id));
        if (!currentExternal && !historicalExternal && !rulesExternal) return true;
        Dictionary<string, List<SchemaExport>> index = new(StringComparer.Ordinal);
        INamedTypeSymbol? marker = compilation.GetTypeByMetadataName(SchemaExportAttributeName);
        if (marker is not null && marker.ContainingAssembly.Identity.Name == "Atelia.DurableGraph" && marker.DeclaringSyntaxReferences.Length == 0) {
            HashSet<ISymbol> indexedAssemblies = new(SymbolEqualityComparer.Default);
            foreach (IAssemblySymbol assembly in compilation.SourceModule.ReferencedAssemblySymbols) {
                if (!indexedAssemblies.Add(assembly)) continue;
                foreach (AttributeData attribute in assembly.GetAttributes()) {
                    if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, marker) ||
                        attribute.ConstructorArguments.Length != 4 || attribute.ConstructorArguments[1].Value is not string id) continue;
                    if (!index.TryGetValue(id, out List<SchemaExport>? entries)) index.Add(id, entries = new());
                    entries.Add(new SchemaExport(assembly, attribute));
                }
            }
        }
        List<SchemaHistoryReferenceEntry> material = new();
        Dictionary<string, SchemaHistoryModel> resolved = new(StringComparer.Ordinal);
        bool valid = true;
        void Error(string message) {
            context.ReportDiagnostic(Diagnostic.Create(InvalidSchemaExport, Location.None, message));
            valid = false;
        }
        bool Request(string id, int version, int? arity = null, IAssemblySymbol? expectedOwner = null, int depth = 0, bool importedDependency = false, int kind = 2) {
            if (owned.Contains(id)) {
                if (expectedOwner is not null || importedDependency) { Error("definition '" + id + "' is owned locally and is also required as a referenced definition"); return false; }
                // Never substitute imported material for an owned missing historical version.
                return true;
            }
            if (depth >= 256) { Error("referenced exact closure exceeds depth 256"); return false; }
            if (!index.TryGetValue(id, out List<SchemaExport>? exports)) {
                Error("missing exported definition '" + id + "' version " + Number(version) +
                    "; enable DurableGraphGenerateDefinitions=true and rebuild its providing library"); return false;
            }
            IAssemblySymbol owner = exports[0].Owner;
            if (exports.Any(item => !SymbolEqualityComparer.Default.Equals(owner, item.Owner)) ||
                (expectedOwner is not null && !SymbolEqualityComparer.Default.Equals(owner, expectedOwner))) {
                Error("definition '" + id + "' has multiple or inconsistent assembly owners"); return false;
            }
            string key = Convert.ToBase64String(StrictUtf8.GetBytes(id)) + ":" + Number(version);
            if (resolved.TryGetValue(key, out SchemaHistoryModel previous)) {
                if (previous.Kind != kind || (arity.HasValue && previous.Arity != arity.Value)) { Error("wrong kind or arity for '" + id + "'"); return false; }
                return true;
            }
            SchemaExport[] matches = exports.Where(item => item.Attribute.ConstructorArguments[2].Value is int number && number == version).ToArray();
            if (matches.Length != 1) { Error("missing or duplicate exported version '" + id + "' " + Number(version)); return false; }
            var args = matches[0].Attribute.ConstructorArguments;
            if (args[0].Value is not int contract || contract != (kind == 2 ? 1 : 2) || args[3].Value is not string text) {
                Error("unsupported execution contract for '" + id + "'"); return false;
            }
            if (!text.StartsWith(SchemaHistoryManifestHeader + "\n", StringComparison.Ordinal) || text.IndexOf('\r') >= 0 || !text.EndsWith("\n", StringComparison.Ordinal)) {
                Error("noncanonical exported manifest for '" + id + "'"); return false;
            }
            string historyText = "// durable-graph-schema-history:9" + text.Substring(SchemaHistoryManifestHeader.Length);
            if (!TryParseSchemaHistory(new SchemaHistoryText(owner.Identity.Name + ".dll", historyText), out SchemaHistoryModel shape, out string? error) ||
                shape.SchemaId != id || shape.Version != version || shape.Kind != kind || (arity.HasValue && shape.Arity != arity.Value) ||
                text != RenderTemplateManifest(shape)) {
                Error("invalid exported template for '" + id + "': " + (error ?? "key, kind, arity, or canonical form mismatch")); return false;
            }
            resolved.Add(key, shape);
            selected.Add(shape);
            material.Add(new SchemaHistoryReferenceEntry(owner.Identity.ToString(), id, version, contract, text));
            if (shape.BaseSchema is SchemaReference ancestor && !Request(ancestor.SchemaId, ancestor.Version, ancestor.Type.Arguments.Count,
                depth: depth + 1, importedDependency: true, kind: 1)) return false;
            foreach (SchemaHistoryFieldModel field in shape.Fields) {
                if (field.InlineSchema is SchemaReference child && !Request(child.SchemaId, child.Version, child.Type.Arguments.Count, depth: depth + 1, importedDependency: true)) return false;
            }
            return true;
        }
        // Current fixed fields retain the metadata owner; nominal arguments do not request exact exports.
        foreach (DurableTypeModel type in types) {
            if (GetCurrentBaseReference(type) is SchemaReference ancestor &&
                !SymbolEqualityComparer.Default.Equals(type.Symbol.BaseType!.ContainingAssembly, compilation.Assembly))
                Request(ancestor.SchemaId, ancestor.Version, type.Symbol.BaseType.Arity, type.Symbol.BaseType.ContainingAssembly, kind: 1);
            foreach (DurableFieldModel field in type.Fields) {
                if (field.InlineSchema is not SchemaReference inline) continue;
                INamedTypeSymbol target = InlineDomain(field);
                if (!SymbolEqualityComparer.Default.Equals(target.ContainingAssembly, compilation.Assembly))
                    Request(inline.SchemaId, inline.Version, target.Arity, target.ContainingAssembly);
            }
        }
        foreach (SchemaHistoryModel shape in history) {
            if (shape.BaseSchema is SchemaReference ancestor) Request(ancestor.SchemaId, ancestor.Version, ancestor.Type.Arguments.Count, kind: 1);
            foreach (SchemaHistoryFieldModel field in shape.Fields)
                if (field.InlineSchema is SchemaReference inline) Request(inline.SchemaId, inline.Version, inline.Type.Arguments.Count);
        }
        // Rules are explicitly local. Their retained endpoint types can be the sole import root.
        foreach (IMethodSymbol method in rules) {
            var args = GetAttribute(method.GetAttributes(), ValueProviderAttributeName)!.ConstructorArguments;
            if (args.Length == 4 && args[1].Value is string id && args[2].Value is int from && args[3].Value is int to) {
                Request(id, from); Request(id, to);
            }
        }
        if (!valid) return false;
        if (selected.Count == 0) return true;
        if (!ValidateHistoryClosure(context, selected)) return false;
        List<SchemaHistoryModel> available = new(history);
        available.AddRange(selected);
        if (!ValidateHistoryClosure(context, available) || !ValidateGenericTemplateHistory(context, types, available)) return false;
        foreach (DurableTypeModel type in types) {
            available.RemoveAll(shape => shape.SchemaId == type.SchemaId && shape.Version == type.Version);
            available.Add(CurrentShape(type));
        }
        // Validate the DAG before deriving helper arities; a missing dependency is never guessed dynamic.
        if (!ValidateHistoryClosure(context, available)) return false;
        foreach (SchemaHistoryModel shape in selected) {
            IAssemblySymbol owner = index[shape.SchemaId][0].Owner;
            GenericLayout layout = MakeGenericLayout(shape, available);
            INamedTypeSymbol? family = owner.GetTypeByMetadataName("Atelia.DurableGraph.Generated." + FamilyName(shape.SchemaId));
            INamedTypeSymbol? dto = family?.GetTypeMembers("V" + Number(shape.Version), layout.DynamicFields.Count).SingleOrDefault();
            INamedTypeSymbol? body = family?.GetTypeMembers("BodyV" + Number(shape.Version), layout.DynamicFields.Count * 2).SingleOrDefault();
            if (!ValidateExportExecutionHelpers(compilation, layout, family, dto, body, index)) {
                Error("missing or incompatible public Family/DTO/body execution helpers for '" + shape.SchemaId + "' version " + Number(shape.Version));
            }
        }
        foreach (DurableTypeModel type in types) {
            foreach (DurableFieldModel field in type.Fields) {
                if (field.InlineSchema is not SchemaReference inline) continue;
                INamedTypeSymbol target = InlineDomain(field);
                if (SymbolEqualityComparer.Default.Equals(target.ContainingAssembly, compilation.Assembly)) continue;
                SchemaHistoryModel shape = selected.Single(item => item.SchemaId == inline.SchemaId && item.Version == inline.Version);
                GenericLayout layout = MakeGenericLayout(shape, available);
                INamedTypeSymbol? projection = target.TypeKind == TypeKind.Enum
                    ? target.ContainingAssembly.GetTypeByMetadataName("Atelia.DurableGraph.Generated.EnumProjection_" + FamilyName(inline.SchemaId))?.GetTypeMembers("Projection").SingleOrDefault()
                    : target.GetTypeMembers("__DurableProjection", layout.DynamicFields.Count * 3).SingleOrDefault();
                if (projection?.DeclaredAccessibility != Accessibility.Public || !projection.AllInterfaces.Any(item =>
                    SymbolEqualityComparer.Default.Equals(item.OriginalDefinition, compilation.GetTypeByMetadataName("Atelia.DurableGraph.IValueProjection`2")) &&
                    item.TypeArguments[0] is INamedTypeSymbol domain && SymbolEqualityComparer.Default.Equals(domain.OriginalDefinition, target.OriginalDefinition)))
                    Error("missing or incompatible public current value projection for '" + inline.SchemaId + "'");
            }
        }
        if (valid && material.Count > 0) manifest = SchemaHistoryReferenceProtocol.Render(material);
        return valid;
    }
}
