using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Atelia.DurableGraph.Generator;

public sealed partial class DurableSchemaGenerator {
    private const string BinaryBodyTypeName = "__DurableBinaryBody";
    private const string PayloadNamespace = "global::Atelia.DurableGraph.StateStore.Serialization.";

    private static readonly DiagnosticDescriptor InvalidBinaryBody = new(
        id: "DG0020",
        title: "Invalid durable binary body",
        messageFormat: "Binary body for '{0}' cannot be generated: {1}",
        category: "DurableGraph.Generator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static bool RequestsBinaryBody(INamedTypeSymbol type) {
        AttributeData? attribute = GetAttribute(type.GetAttributes(), DurableTypeAttributeMetadataName);
        if (attribute is not null) {
            foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments) {
                if (argument.Key == "GenerateBinaryBody" && argument.Value.Value is true) {
                    return true;
                }
            }
        }

        return false;
    }

    private static void GenerateBinaryBodies(
        SourceProductionContext context,
        List<DurableTypeModel> types,
        List<DurableTypeModel> validatedSchemaOnlyTypes,
        bool historyParsedSuccessfully) {
        HashSet<ISymbol> eligible = new(SymbolEqualityComparer.Default);
        foreach (DurableTypeModel type in types) {
            if (!RequestsBinaryBody(type.Symbol)) {
                continue;
            }

            bool valid = true;
            if (!IsSchemaOnly(type.Symbol)) {
                ReportInvalidBinaryBody(context, type.Symbol, "GenerateBinaryBody requires SchemaOnly=true");
                valid = false;
            }

            var members = type.Symbol.GetMembers(BinaryBodyTypeName);
            if (type.Symbol.Name == BinaryBodyTypeName || !members.IsEmpty) {
                ReportInvalidBinaryBody(context, type.Symbol,
                    "the generated helper name '" + BinaryBodyTypeName + "' is reserved");
                valid = false;
            }

            foreach (DurableFieldModel field in type.Fields) {
                if (field.TypeTagValue != 1 && field.TypeTagValue != 2 && field.TypeTagValue != 3) {
                    ReportInvalidBinaryBody(context, type.Symbol,
                        "field '" + field.Symbol.Name + "' requires reference identity support; this body supports only bool, int and long",
                        GetSourceLocation(field.Symbol));
                    valid = false;
                }
            }

            if (valid && validatedSchemaOnlyTypes.Exists(candidate =>
                SymbolEqualityComparer.Default.Equals(candidate.Symbol, type.Symbol))) {
                eligible.Add(type.Symbol);
            }
        }

        // Damaged input cannot reliably be attributed to one schema. Never expose a usable body from it.
        if (!historyParsedSuccessfully) {
            return;
        }

        StringBuilder source = new("// <auto-generated/>\n#nullable enable\n");
        bool emitted = false;
        foreach (DurableTypeModel type in types) {
            if (!eligible.Contains(type.Symbol)) {
                continue;
            }

            INamedTypeSymbol? ancestor = type.Symbol.BaseType;
            bool valid = true;
            while (!HasMetadataName(ancestor, DurableBaseMetadataName)) {
                if (ancestor is null || !eligible.Contains(ancestor)) {
                    ReportInvalidBinaryBody(context, type.Symbol,
                        "every domain ancestor must enable GenerateBinaryBody and pass metadata, history and binary body validation");
                    valid = false;
                    break;
                }

                ancestor = ancestor.BaseType;
            }

            if (valid) {
                AppendBinaryBodyType(source, type);
                emitted = true;
            }
        }

        if (emitted) {
            context.AddSource("DurableBinaryBodies.g.cs",
                SourceText.From(source.ToString().Replace("\r\n", "\n"), Encoding.UTF8));
        }
    }

    private static void ReportInvalidBinaryBody(
        SourceProductionContext context, INamedTypeSymbol type, string message, Location? location = null) {
        context.ReportDiagnostic(Diagnostic.Create(InvalidBinaryBody,
            location ?? GetSourceLocation(type), type.ToDisplayString(QualifiedNameFormat), message));
    }

    private static void AppendBinaryBodyType(StringBuilder source, DurableTypeModel type) {
        bool hasNamespace = !type.Symbol.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace) {
            source.Append("namespace ").Append(type.Symbol.ContainingNamespace.ToDisplayString(QualifiedNameFormat)).AppendLine(" {");
        }

        string indent = hasNamespace ? "    " : string.Empty;
        string member = indent + "    ";
        bool hasDomainBase = GetCurrentBaseReference(type.Symbol).HasValue;
        source.Append(indent).Append("partial class ").Append(EscapeIdentifier(type.Symbol.Name)).AppendLine(" {");
        source.Append(member).Append("internal ").Append(hasDomainBase ? "new " : string.Empty)
            .Append("static class ").Append(BinaryBodyTypeName).AppendLine(" {");
        AppendBinaryBodyMethod(source, type, member + "    ", hasDomainBase, isRead: false);
        AppendBinaryBodyMethod(source, type, member + "    ", hasDomainBase, isRead: true);
        source.Append(member).AppendLine("}");
        source.Append(indent).AppendLine("}");
        if (hasNamespace) {
            source.AppendLine("}");
        }
    }

    private static void AppendBinaryBodyMethod(
        StringBuilder source, DurableTypeModel type, string indent, bool hasDomainBase, bool isRead) {
        string operation = isRead ? "Read" : "Write";
        string payloadName = isRead ? "reader" : "writer";
        source.Append(indent).Append("internal static void ").Append(operation).Append("(ref ")
            .Append(PayloadNamespace).Append(isRead ? "BinaryPayloadReader" : "BinaryPayloadWriter")
            .Append(' ').Append(payloadName).Append(", ")
            .Append(type.Symbol.ToDisplayString(FullyQualifiedNameFormat)).AppendLine(" value) {");
        source.Append(indent).AppendLine("    global::System.ArgumentNullException.ThrowIfNull(value);");
        if (hasDomainBase) {
            source.Append(indent).Append("    ")
                .Append(type.Symbol.BaseType!.ToDisplayString(FullyQualifiedNameFormat))
                .Append('.').Append(BinaryBodyTypeName).Append('.').Append(operation)
                .Append("(ref ").Append(payloadName).AppendLine(", value);");
        }

        foreach (DurableFieldModel field in type.Fields) {
            string fieldAccess = "value." + EscapeIdentifier(field.Symbol.Name);
            source.Append(indent).Append("    ");
            if (isRead) {
                source.Append(fieldAccess).Append(" = reader.Read").Append(field.TypeTag).AppendLine("();");
            } else {
                source.Append("writer.Write").Append(field.TypeTag).Append('(').Append(fieldAccess).AppendLine(");");
            }
        }

        source.Append(indent).AppendLine("}");
    }
}
