<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\atelia\src\Data\Data.csproj" />
    <ProjectReference Include="..\..\..\atelia\src\RbfSegmentStore\RbfSegmentStore.csproj" />
  </ItemGroup>

</Project>
